apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: epic-artist-management
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: epic-artist-management
    spec:
      containers:
      - name: epic-artist-management
        image: eu.gcr.io/cluster-01-1252/epic-artist-management:latest
        ports:
        - containerPort: 3000
