apiVersion: v1
kind: Service
metadata:
  name: node-plus-website
  labels:
    name: node-plus-website
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: node-plus-website
