apiVersion: v1
kind: Service
metadata:
  name: epic-artsit-management
  labels:
    name: epic-artsit-management
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: epic-artsit-management
